<img src='Exercício.png'>

In [4]:
import numpy as np 

In [1]:
# matriz força

# n = quantidade de forças
n = 2
matriz_forca = []

for i in range(0,n):
    matriz_forca.append(list())
for i in range(0,n):
    for j in range(0,3):
        matriz_forca[i].append(list())
for i in range(0,n):
    for j in range(0,3):
        matriz_forca[i][j].append(int(input(f'elemento[{i}x{j}]:')))

for i in range(0,n):
    print(f'{matriz_forca[i]}')

KeyboardInterrupt: Interrupted by user

In [2]:
# matriz posição
matriz_posicao = []

for i in range(0,n):
    matriz_posicao.append(list())
for i in range(0,n):
    for j in range(0,3):
        matriz_posicao[i].append(list())
for i in range(0,n):
    for j in range(0,3):
        matriz_posicao[i][j].append(int(input(f'elemento[{i}x{j}]:')))

for i in range(0,n):
    print(f'{matriz_posicao[i]}')

elemento[0x0]:5
elemento[0x1]:1
elemento[0x2]:1
elemento[1x0]:1
elemento[1x1]:3
elemento[1x2]:6
[[5], [1], [1]]
[[1], [3], [6]]


In [29]:
# vetor posição
r = [[5, -2, 3],[3, 2, 2]]

# vetor força
f = [[80, -30, -70],[80, 5, 60]]


produto_vetorial = np.cross(r, f) 
print(produto_vetorial)

[[ 230  590   10]
 [ 110  -20 -145]]


In [2]:
matriz_posicao = [[0, 0, 0.1],[0.16, -0.08, 0.18],[0.16, 0.08, 0.18],[0.08, 0, 0.26]]
matriz_forca  = [[0, 50, 0],[80, 0, 0],[0, 0, 60],[0, 40, 0]]
matriz_momento = [[0, 15, 0],[0, 0, 20]]
print(f'{matriz_posicao}')
print(f'{matriz_forca}')

[[0, 0, 0.1], [0.16, -0.08, 0.18], [0.16, 0.08, 0.18], [0.08, 0, 0.26]]
[[0, 50, 0], [80, 0, 0], [0, 0, 60], [0, 40, 0]]


In [6]:
i = 0
a = []

while i < len(matriz_posicao):
    prod = np.cross(matriz_posicao[i], matriz_forca[i])
    prod = a.append(prod)
    prod = sum(a)
    i = i + 1

if matriz_momento == '':
    print(prod)
else:
    matriz_momento = np.sum(matriz_momento, axis=0)
    prod = prod + matriz_momento
    print(prod)

[24.4 39.8 44.6]


C:\Users\Uello\AppData\Local\Temp\ipykernel_2252\3443494043.py:10: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if matriz_momento == '':
